CREATE TABLE IF NOT EXISTS HoTroNhanh (
 id INT PRIMARY KEY AUTO_INCREMENT,
 guestHash CHAR(64) NOT NULL,
 activeGuest CHAR(64) NULL UNIQUE,
 state VARCHAR(24) NOT NULL DEFAULT 'waiting',
 dispatcher INT NULL,
 technician INT NULL,
 lat DECIMAL(10,8) NULL,
 lng DECIMAL(11,8) NULL,
 locationText VARCHAR(500) NOT NULL DEFAULT '',
 phone VARCHAR(15) NOT NULL DEFAULT '',
 vehicle VARCHAR(40) NOT NULL DEFAULT '',
 issue VARCHAR(500) NOT NULL DEFAULT '',
 plan TEXT,
 eta INT NULL,
 price BIGINT NULL,
 priceNote VARCHAR(500) NOT NULL DEFAULT '',
 version INT NOT NULL DEFAULT 0,
 createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (dispatcher) REFERENCES TaiKhoan(MaTaiKhoan),
 FOREIGN KEY (technician) REFERENCES TaiKhoan(MaTaiKhoan),
 INDEX idx_support_state(state,createdAt),
 INDEX idx_support_guest(guestHash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS HoTroTinNhan (
 id INT PRIMARY KEY AUTO_INCREMENT,
 requestId INT NOT NULL,
 sender VARCHAR(20) NOT NULL,
 author VARCHAR(100) NOT NULL,
 body TEXT,
 mime VARCHAR(60),
 media MEDIUMBLOB,
 createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (requestId) REFERENCES HoTroNhanh(id),
 INDEX idx_support_messages(requestId,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS CaTrucCuuHo (
 accountId INT PRIMARY KEY,
 available TINYINT NOT NULL DEFAULT 0,
 area VARCHAR(150) NOT NULL DEFAULT '',
 capability VARCHAR(150) NOT NULL DEFAULT '',
 seenAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(accountId) REFERENCES TaiKhoan(MaTaiKhoan)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS DiemCuuHo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  address VARCHAR(500) NOT NULL,
  phone VARCHAR(20) NOT NULL DEFAULT '',
  lat DECIMAL(10,8) NOT NULL,
  lng DECIMAL(11,8) NOT NULL,
  active TINYINT NOT NULL DEFAULT 1,
  isDemo TINYINT NOT NULL DEFAULT 0,
  demoKey VARCHAR(40) NULL UNIQUE,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NhanVienTram (
 accountId INT PRIMARY KEY,
 stationId INT NOT NULL,
 manager TINYINT NOT NULL DEFAULT 0,
 FOREIGN KEY(accountId) REFERENCES TaiKhoan(MaTaiKhoan),
 FOREIGN KEY(stationId) REFERENCES DiemCuuHo(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS XeCuuHoTram (
 id INT AUTO_INCREMENT PRIMARY KEY,
 stationId INT NOT NULL,
 name VARCHAR(150) NOT NULL,
 plate VARCHAR(30) NOT NULL UNIQUE,
 capability VARCHAR(150) NOT NULL DEFAULT '',
 active TINYINT NOT NULL DEFAULT 1,
 FOREIGN KEY(stationId) REFERENCES DiemCuuHo(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS HoTroTramTuChoi (
 requestId INT NOT NULL,
 stationId INT NOT NULL,
 reason VARCHAR(500) NOT NULL,
 PRIMARY KEY(requestId,stationId),
 FOREIGN KEY(requestId) REFERENCES HoTroNhanh(id),
 FOREIGN KEY(stationId) REFERENCES DiemCuuHo(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
